export const familyMembers = [
  {
    name: "Queen Anga",
    gender: "Female",
    parentId: null,
    spouseId: "King Shan",
  },
  {
    name: "King Shan",
    gender: "Male",
    parentId: null,
    spouseId: "Queen Anga",
  },
  {
    name: "Chit",
    gender: "Male",
    parentId: "Queen Anga",
    spouseId: "Amba",
  },
  {
    name: "Ish",
    gender: "Male",
    parentId: "Queen Anga",
    spouseId: null,
  },
  {
    name: "Vich",
    gender: "Male",
    parentId: "Queen Anga",
    spouseId: "Lika",
  },
  {
    name: "Aras",
    gender: "Male",
    parentId: "Queen Anga",
    spouseId: "Chitra",
  },
  {
    name: "Satya",
    gender: "Female",
    parentId: "Queen Anga",
    spouseId: "Vyan",
  },
  {
    name: "Dritha",
    gender: "Female",
    parentId: "Amba",
    spouseId: "Jaya",
  },
  {
    name: "Tritha",
    gender: "Female",
    parentId: "Amba",
    spouseId: null,
  },
  {
    name: "Vritha",
    gender: "Male",
    parentId: "Amba",
    spouseId: null,
  },
  {
    name: "Vila",
    gender: "Female",
    parentId: "Lika",
    spouseId: null,
  },
  {
    name: "Chika",
    gender: "Female",
    parentId: "Lika",
    spouseId: null,
  },
  {
    name: "Yodhan",
    gender: "Male",
    parentId: "Dritha",
    spouseId: null,
  },
  {
    name: "Jnki",
    gender: "Female",
    parentId: "Chitra",
    spouseId: "Arit",
  },
  {
    name: "Ahit",
    gender: "Male",
    parentId: "Chitra",
    spouseId: null,
  },
  {
    name: "Lavnya",
    gender: "Female",
    parentId: "Jnki",
    spouseId: null,
  },
  {
    name: "Laki",
    gender: "Male",
    parentId: "Jnki",
    spouseId: null,
  },
  {
    name: "Asva",
    gender: "Male",
    parentId: "Satya",
    spouseId: "Satvy",
  },
  {
    name: "Vyas",
    gender: "Male",
    parentId: "Satya",
    spouseId: "Krpi",
  },
  {
    name: "Atya",
    gender: "Female",
    parentId: "Satya",
    spouseId: null,
  },
  {
    name: "Vasa",
    gender: "Male",
    parentId: "Satvy",
    spouseId: null,
  },
  {
    name: "Krithi",
    gender: "Female",
    parentId: "Krpi",
    spouseId: null,
  },
  {
    name: "Kriya",
    gender: "Male",
    parentId: "Krpi",
    spouseId: null,
  },
  {
    name: "Amba",
    gender: "Female",
    parentId: null,
    spouseId: "Chit",
  },
  {
    name: "Jaya",
    gender: "Male",
    parentId: null,
    spouseId: "Dritha",
  },
  {
    name: "Lika",
    gender: "Female",
    parentId: null,
    spouseId: "Vich",
  },
  {
    name: "Chitra",
    gender: "Female",
    parentId: null,
    spouseId: "Aras",
  },
  {
    name: "Arit",
    gender: "Male",
    parentId: null,
    spouseId: "Jnki",
  },
  {
    name: "Vyan",
    gender: "Male",
    parentId: null,
    spouseId: "Satya",
  },
  {
    name: "Satvy",
    gender: "Female",
    parentId: null,
    spouseId: "Asva",
  },
  {
    name: "Krpi",
    gender: "Female",
    parentId: null,
    spouseId: "Vyas",
  },
];
