export const CHILD_ADDITION_SUCCEEDED = 'CHILD_ADDITION_SUCCEEDED';
export const CHILD_ADDITION_FAILED = 'CHILD_ADDITION_FAILED';
export const PERSON_NOT_FOUND = 'PERSON_NOT_FOUND';
export const NONE = 'NONE';
export const UNKNOWN_ACTION = 'UNKNOWN ACTION';
